<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IBASE132-PC" name="OWyseTest" tests="1" failures="0" timestamp="26 May 2016 09:57:22 GMT" time="36.741" errors="1">
  <testcase name="f" time="36.741" classname="OWyseTest">
    <error type="java.lang.reflect.InvocationTargetException">
      <![CDATA[java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.omniwyse.mobiletest.test.functions.AppFunctionStep.execute(AppFunctionStep.java:73)
	at com.omniwyse.mobiletest.test.cases.TestCaseStep.execute(TestCaseStep.java:52)
	at com.omniwyse.mobiletest.test.cases.TestCaseStep.executeTestCaseStep(TestCaseStep.java:39)
	at com.omniwyse.mobiletest.test.cases.TestCaseStep.<init>(TestCaseStep.java:27)
	at com.omniwyse.mobiletest.test.cases.TestCases.executeTestCase(TestCases.java:42)
	at com.omniwyse.mobiletest.test.cases.TestCases.<init>(TestCases.java:26)
	at com.omniwyse.mobiletest.test.suites.TestSuite.<init>(TestSuite.java:37)
	at com.omniwyse.mobiletest.data.DataManager.executeTestPlan(DataManager.java:66)
	at OWyseTest.f(OWyseTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: javax.mail.AuthenticationFailedException: [ALERT] Invalid credentials (Failure)
	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:474)
	at javax.mail.Service.connect(Service.java:275)
	at javax.mail.Service.connect(Service.java:156)
	at com.omniwyse.mobiletest.utils.GmailUtility.getEmailStore(GmailUtility.java:55)
	at com.omniwyse.mobiletest.utils.GmailUtility.getVerificationLinkFromGmail(GmailUtility.java:140)
	at com.omniwyse.mobiletest.driver.SeleniumFramework.registerAndValidateUser(SeleniumFramework.java:715)
	... 37 more
]]>
    </error>
  </testcase> <!-- f -->
</testsuite> <!-- OWyseTest -->
